USE [master]
GO

/****** Object:  Database [Vekka]    Script Date: 14.07.2021 02:06:14 ******/
CREATE DATABASE [Vekka]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vekka', FILENAME = N'D:\Satılabilecek Otomasyonlar\C# SQL\Vekka\veritabani\Vekka.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Vekka_log', FILENAME = N'D:\Satılabilecek Otomasyonlar\C# SQL\Vekka\veritabani\Vekka_log.ldf' , SIZE = 3136KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Vekka] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Vekka].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Vekka] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Vekka] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Vekka] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Vekka] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Vekka] SET ARITHABORT OFF 
GO

ALTER DATABASE [Vekka] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Vekka] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Vekka] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Vekka] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Vekka] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Vekka] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Vekka] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Vekka] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Vekka] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Vekka] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Vekka] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Vekka] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Vekka] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Vekka] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Vekka] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Vekka] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Vekka] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Vekka] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Vekka] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Vekka] SET  MULTI_USER 
GO

ALTER DATABASE [Vekka] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Vekka] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Vekka] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Vekka] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Vekka] SET  READ_WRITE 
GO

